image: golang:1.10

stages:
  - build
  - test

before_script:
  - go get -u -v github.com/golang/dep/cmd/dep
  - cp -r /builds/rfaulhaber /go/src/github.com/rfaulhaber
  - cd /go/src/github.com/rfaulhaber/clock
  - dep ensure -v

build-project:
  stage: build
  script:
    - go build -v

test-project:
  stage: test
  script:
    - go test -v -cover ./...

